"""Aggregate the five-run (seeds 100-104) expert-novice robustness check.

Usage:
    python scripts/aggregate_robustness.py

Prints the median (min--max) paired expert-minus-novice difference and the
same-direction count for each measure in Table~tab:robustness, and the raw
LaTeX table rows ready to paste into the manuscript.
"""

import json
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from config.defaults import DEFAULT_DT, MODEL_VERSION, NETWORKS, PLOT_STEPS, STATES
from viz.analysis_utils import compute_network_profiles, compute_tail_statistics
from viz.ignition import access_summary

DATA = ROOT / "data"
OUT = ROOT / "figures" / "robustness.tex"
SEEDS = (100, 101, 102, 103, 104)

MEASURES = [
    ("Breath Focus dwell (s)", "dwell", "breath_focus", 1),
    ("Mind Wandering dwell (s)", "dwell", "mind_wandering", 1),
    ("Breath Focus DMN", "network", ("breath_focus", "DMN"), 3),
    ("Breath Focus DAN", "network", ("breath_focus", "DAN"), 3),
    ("Breath Focus FPN", "network", ("breath_focus", "FPN"), 3),
    ("RA$\\rightarrow$BF transition", "transition", ("redirect_attention", "breath_focus"), 3),
    ("MW$\\rightarrow$MA transition", "transition", ("mind_wandering", "meta_awareness"), 3),
    ("Breath access run (s)", "access", "breath_run_seconds", 2),
    ("Mean $m_t$ over the window", "access", "meta_awareness_session", 3),
    ("Mean $m_t$ in Breath Focus", "access", "meta_awareness_bf", 3),
]


def _load(phenotype: str, seed: int) -> dict:
    with (DATA / f"training_results_{phenotype}_seed{seed}.json").open() as handle:
        return json.load(handle)


def _diffs_for_seed(seed: int) -> dict:
    expert = _load("expert", seed)
    novice = _load("novice", seed)
    e_profile = compute_network_profiles(expert, STATES, NETWORKS, PLOT_STEPS)
    n_profile = compute_network_profiles(novice, STATES, NETWORKS, PLOT_STEPS)
    e_tail = compute_tail_statistics(expert, STATES, PLOT_STEPS)
    n_tail = compute_tail_statistics(novice, STATES, PLOT_STEPS)

    out = {}
    for label, kind, key, _ in MEASURES:
        if kind == "dwell":
            out[label] = DEFAULT_DT * (e_tail["dwell_times"][key] - n_tail["dwell_times"][key])
        elif kind == "network":
            state, network = key
            out[label] = e_profile[state][network] - n_profile[state][network]
        elif kind == "transition":
            source, destination = key
            e_val = e_tail["transition_matrix"][source].get(destination, 0.0)
            n_val = n_tail["transition_matrix"][source].get(destination, 0.0)
            out[label] = e_val - n_val
        elif kind == "access":
            out[label] = access_summary(expert, PLOT_STEPS)[key] - access_summary(novice, PLOT_STEPS)[key]
    return out


def main() -> None:
    per_seed = {seed: _diffs_for_seed(seed) for seed in SEEDS}

    print(f"{'Measure':32s} {'median':>10s} {'min':>10s} {'max':>10s}  direction")
    rows = []
    for label, _, _, digits in MEASURES:
        values = np.array([per_seed[seed][label] for seed in SEEDS])
        median = float(np.median(values))
        lo, hi = float(values.min()), float(values.max())
        same_direction = int(np.sum(np.sign(values) == np.sign(median))) if median != 0 else int(np.sum(values == 0))
        print(f"{label:32s} {median:10.3f} {lo:10.3f} {hi:10.3f}  {same_direction}/{len(SEEDS)}")

        def fmt(value: float, sign_digits: int) -> str:
            return f"${value:+.{sign_digits}f}$"

        rows.append(
            f"{label} & {fmt(median, digits)} ({fmt(lo, digits)}--{fmt(hi, digits)}) & {same_direction}/{len(SEEDS)}\\\\"
        )

    print("\nLaTeX table rows:\n")
    for row in rows:
        print(row)

    table = [
        "% Auto-generated by scripts/aggregate_robustness.py; do not edit by hand.",
        f"% Model version: {MODEL_VERSION}.",
        rf"\def\RobustnessModelVersion{{{MODEL_VERSION}}}",
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{\textbf{Five-run qualitative robustness check.} Paired expert-minus-novice differences over the final \StatsPlotSteps{} steps; values are median (minimum--maximum) across training seeds 100--104. Positive dwell differences indicate longer expert mean dwell durations. Direction counts runs whose difference has the same sign as the median; when the median is zero, it counts zero differences.}",
        r"\small",
        r"\begin{tabular}{l c c}",
        r"\hline",
        r"Measure & Paired difference & Direction\\",
        r"\hline",
        *rows,
        r"\hline",
        r"\end{tabular}",
        r"\label{tab:robustness}",
        r"\end{table}",
    ]
    OUT.write_text("\n".join(table) + "\n", encoding="utf-8")
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
