"""Export manuscript statistics from the pinned figure-seed result artifacts.

Usage:
    python scripts/export_stats.py

Writes figures/stats.tex.  Stage G manuscript text must use these macros rather
than manually copied values.
"""

import argparse
import json
from pathlib import Path
import sys

import numpy as np
from sklearn.decomposition import PCA

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from config.defaults import DEFAULT_DT, MODEL_VERSION, NETWORKS, PLOT_STEPS, PRACTICE_OBJECT, STATES, THOUGHTSEEDS
from experiments.training_pipeline import SEED
from viz.analysis_utils import compute_network_profiles, compute_tail_statistics
from viz.ignition import access_summary, detection_summary


DATA = ROOT / "data"
OUT = ROOT / "figures" / "stats.tex"


def _load(phenotype: str, seed: int) -> dict:
    with (DATA / f"training_results_{phenotype}_seed{seed}.json").open() as handle:
        return json.load(handle)


def _macro(name: str, value: str) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def _f(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def _pca_level_stats(novice_feat: np.ndarray, expert_feat: np.ndarray,
                      novice_states: list, expert_states: list) -> tuple:
    """Reproduce viz/attractors.py's PCA (fit jointly, project each phenotype)
    and compute each state's mean distance-to-centroid (cluster spread)."""
    pca = PCA(n_components=2)
    pca.fit(np.concatenate([novice_feat, expert_feat], axis=0))
    var_ratio = pca.explained_variance_ratio_
    novice_proj = pca.transform(novice_feat)
    expert_proj = pca.transform(expert_feat)

    def spread(proj: np.ndarray, states: list, target: str) -> float:
        idx = [i for i, s in enumerate(states) if s == target]
        points = proj[idx]
        centroid = points.mean(axis=0)
        return float(np.mean(np.linalg.norm(points - centroid, axis=1)))

    ratios = {
        state: spread(expert_proj, expert_states, state) / spread(novice_proj, novice_states, state)
        for state in ("breath_focus", "meta_awareness")
    }
    return var_ratio, ratios


def _pca_stats(expert_run: dict, novice_run: dict) -> list:
    def thoughtseed_tail(run: dict) -> np.ndarray:
        return np.asarray(run["thoughtseed_activations_history"][-PLOT_STEPS:], dtype=float)

    def network_tail(run: dict) -> np.ndarray:
        rows = run["network_activations_history"][-PLOT_STEPS:]
        return np.asarray([[row[net] for net in NETWORKS] for row in rows], dtype=float)

    def state_tail(run: dict) -> list:
        return run["state_history"][-PLOT_STEPS:]

    novice_states, expert_states = state_tail(novice_run), state_tail(expert_run)

    var_l2, ratios_l2 = _pca_level_stats(
        thoughtseed_tail(novice_run), thoughtseed_tail(expert_run), novice_states, expert_states,
    )
    var_l1, ratios_l1 = _pca_level_stats(
        network_tail(novice_run), network_tail(expert_run), novice_states, expert_states,
    )

    return [
        _macro("PCAThoughtseedPCOneVariance", _f(100 * var_l2[0], 1)),
        _macro("PCAThoughtseedPCTwoVariance", _f(100 * var_l2[1], 1)),
        _macro("PCAThoughtseedCombinedVariance", _f(100 * sum(var_l2), 1)),
        _macro("PCANetworkPCOneVariance", _f(100 * var_l1[0], 1)),
        _macro("PCANetworkPCTwoVariance", _f(100 * var_l1[1], 1)),
        _macro("PCANetworkCombinedVariance", _f(100 * sum(var_l1), 1)),
        _macro("PCABreathFocusSpreadRatioThoughtseed", _f(ratios_l2["breath_focus"], 2)),
        _macro("PCABreathFocusSpreadRatioNetwork", _f(ratios_l1["breath_focus"], 2)),
        _macro("PCAMetaAwarenessSpreadRatioThoughtseed", _f(ratios_l2["meta_awareness"], 2)),
        _macro("PCAMetaAwarenessSpreadRatioNetwork", _f(ratios_l1["meta_awareness"], 2)),
    ]


def main(seed: int = SEED) -> None:
    results = {name: _load(name, seed) for name in ("expert", "novice")}
    (fit_seed,) = {run["seed"] for run in results.values()}
    (rollout_seed,) = {run["evaluation_seed"] for run in results.values()}
    lines = [
        "% Auto-generated by scripts/export_stats.py; do not edit by hand.",
        f"% Source: training_results_{{expert,novice}}_seed{fit_seed}.json.",
        f"% Model version: {MODEL_VERSION}.",
        _macro("StatsModelVersion", MODEL_VERSION),
        _macro("StatsSeed", str(fit_seed)),
        _macro("StatsRolloutSeed", str(rollout_seed)),
        _macro("StatsPlotSteps", f"{PLOT_STEPS:,}"),
    ]

    for phenotype, run in results.items():
        prefix = phenotype.title()
        profiles = compute_network_profiles(run, STATES, NETWORKS, PLOT_STEPS)
        tail = compute_tail_statistics(run, STATES, PLOT_STEPS)
        tail_start = len(run["state_history"]) - PLOT_STEPS
        ma_exits = sum(
            1 for transition in run.get("transitions", [])
            if transition.get("timestamp", -1) >= tail_start
            and transition.get("from") == "meta_awareness"
        )
        mw_exits = tail["transition_exit_counts"]["mind_wandering"]
        ra_exits = tail["transition_exit_counts"]["redirect_attention"]
        for state in STATES:
            state_macro = "".join(part.title() for part in state.split("_"))
            lines.append(_macro(
                f"{prefix}Dwell{state_macro}", _f(DEFAULT_DT * tail["dwell_times"][state], 1),
            ))
            for network in NETWORKS:
                net_macro = network.upper()
                lines.append(_macro(
                    f"{prefix}{state_macro}{net_macro}", _f(profiles[state][network]),
                ))
            for destination, probability in tail["transition_matrix"][state].items():
                if destination != state:
                    dest_macro = "".join(part.title() for part in destination.split("_"))
                    lines.append(_macro(
                        f"{prefix}Transition{state_macro}To{dest_macro}", _f(probability, 2),
                    ))

        # Access and meta-awareness stats use the same final-PLOT_STEPS window
        # as Fig. 4 and every other main-text figure.
        access = access_summary(run, PLOT_STEPS)
        detection = detection_summary(run, PLOT_STEPS)
        for suffix, key in (
            ('DetectionCount', 'detected_ma_episodes'),
            ('DetectedRAExits', 'direct_ra_exits'),
            ('DetectedOtherExits', 'other_exits'),
            ('DetectedUnresolved', 'unresolved_detected_episodes'),
        ):
            lines.append(_macro(f'{prefix}{suffix}', str(detection[key])))
        for suffix, key in (
            ('DetectionLatency', 'detection_latency_seconds'),
            ('RedirectionLatency', 'redirection_latency_seconds'),
            ('MAPreDetection', 'ma_pre_detection_seconds'),
            ('MAPostDetection', 'ma_post_detection_seconds'),
        ):
            value = detection[key]
            lines.append(_macro(f'{prefix}{suffix}', '--' if value is None else _f(value, 2)))
        breath_prior = run["access_prior"][THOUGHTSEEDS.index(PRACTICE_OBJECT)]
        lines.extend([
            _macro(f"{prefix}MAExitCount", str(ma_exits)),
            _macro(f"{prefix}MWExitCount", str(mw_exits)),
            _macro(f"{prefix}RAExitCount", str(ra_exits)),
            _macro(f"{prefix}PracticeSteps", f"{int(run['training_steps']):,}"),
            _macro(f"{prefix}AccessEvents", str(int(access["access_onsets"]))),
            _macro(f"{prefix}BreathAccessPercent", _f(access["breath_access_percent"], 1)),
            _macro(f"{prefix}BreathRunSeconds", _f(access["breath_run_seconds"], 1)),
            _macro(f"{prefix}DistractorAccessMWPercent", _f(access["distractor_access_mw_percent"], 1)),
            _macro(f"{prefix}MetaAwarenessBF", _f(access["meta_awareness_bf"], 2)),
            _macro(f"{prefix}MetaAwarenessSession", _f(access["meta_awareness_session"], 2)),
            _macro(f"{prefix}MetaEpisodes", str(int(access["meta_episodes"]))),
            _macro(f"{prefix}BreathAccessPrior", _f(breath_prior, 2)),
        ])

    lines.extend(_pca_stats(results["expert"], results["novice"]))

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export manuscript statistics for one saved fit seed.")
    parser.add_argument("--seed", type=int, default=SEED,
                        help=f"fit seed to export (default: {SEED})")
    main(parser.parse_args().seed)
